name: 'Yarn'

description: 'Install node modules'

runs:
  using: 'composite'
  steps:
    - name: Yarn Cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn Install
      shell: bash
      run: yarn install --immutable

    - name: Yarn Install Peer
      shell: bash
      run: yarn add wavesurfer.js
